// <auto-generated />
namespace ProyectoPrograAvanzadaG.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class EnsureDatabaseUpToDate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EnsureDatabaseUpToDate));
        
        string IMigrationMetadata.Id
        {
            get { return "202408052343038_EnsureDatabaseUpToDate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
